pipeline {
    agent any

    stages {
        stage("Checkout") {
            steps {
                checkout scm
            }
        }

        stage('Install npm dependencies') {
            steps {
                dir('PEP1_Tingeso_Frontend') {
                    bat 'npm install'
                }
            }
        }

        stage('Run npm build') {
            steps {
                dir('PEP1_Tingeso_Frontend') {
                    bat 'npm run build'
                }
            }
        }

        stage('Build docker image') {
            steps {
                dir('PEP1_Tingeso_Frontend') {
                    bat 'docker build -t agustinsaavedra056/pep1_tingeso_frontend:latest .'
                }
            }
        }

        stage('Push image to Docker Hub') {
            steps {
                dir('PEP1_Tingeso_Frontend') {
                    withCredentials([string(credentialsId: 'dhpswid', variable: 'dhpsw')]) {
                        bat 'docker login -u agustinsaavedra056 -p %dhpsw%'
                    }
                    bat 'docker push agustinsaavedra056/pep1_tingeso_frontend:latest'
                }
            }
        }
    }
}
